version: "3.3"

services:
    db:
        image: postgres
        volumes:
            - data:/var/lib/postgresql/data
        env_file:
            - db-local.env
        ports:
            - "5432:5432"
        networks:
            - net
    myhackwashu:
        build: .
        env_file:
            - db-local.env
            - app.env
        environment:
            - "POSTGRES_HOST=db"
        volumes:
            - .:/registration
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: /bin/sh -c "sh restart-docker.sh && python manage.py runserver 0.0.0.0:8000"
        networks:
            - net
volumes:
    data:

networks:
    net:
        driver: bridge
