version: "3.3"

services:
    db:
        image: postgres
        volumes:
            - data:/var/lib/postgresql/data
        env_file:
            - db.env
        ports:
            - "5432:5432"
        networks:
            - appnet
    myhackwashu:
        build: .
        env_file:
            - db-local.env
            - app.env
        volumes:
            - .:/registration
        ports:
            - "80:80"
        depends_on:
            - db
        command: /bin/sh -c "sh restart-docker.sh && python manage.py runserver 0.0.0.0:80"
        networks:
            - appnet
volumes:
    data:

networks:
    appnet:
        driver: bridge