version: "3.3"

services:
    db:
        image: postgres
        volumes:
            - data:/var/lib/postgresql/data
        env_file:
            - db.env
        container_name: "postgres"
    myhackwashu:
        build: .
        platform: linux/amd64
        env_file:
            - db.env
            - app.env
        volumes:
            - .:/registration
        ports:
            - "80:80"
        links:
            - db:db
        depends_on:
            - db
        command: /bin/sh -c "/registration/restart-docker.sh && python manage.py runserver 0.0.0.0:80"
volumes:
    data:
