version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - db.env
    container_name: "postgres"
  myhackwashu:
    build: .
    env_file:
      - app.env
    ports:
      - "80:80"
    links:
            - db:db
    depends_on:
            - db
    command: sh server.sh
